eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**
        - id:
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter
        - id:
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthFilter


server:
  port: 8060