eureka:
  instance:
    preferIpAddress: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/


server:
  port: 8083


spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: order-service
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/orderdb
    username: order
    password: order
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
